# Generated by Django 4.1.2 on 2022-10-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("albumId", models.IntegerField()),
                (
                    "image_file",
                    models.ImageField(
                        height_field="image_height",
                        upload_to="photos",
                        width_field="image_width",
                    ),
                ),
                ("image_width", models.IntegerField()),
                ("image_height", models.IntegerField()),
                ("image_url", models.URLField()),
            ],
        ),
    ]
